#ifndef DEFS_H
#define DEFS_H

#include <QToolBar>

typedef QToolBar ToolBar;

// Will be generated by make via call to HG
extern const char* HG_REPRO_ID;
extern const char* HG_REPRO_REV;
extern const char* HG_REPRO_DATE;
extern const char* BUILD_DATE;
extern const char* BUILD_TIME;

#endif // DEFS_H
