/**********************************************************************
  Copyright (C) 2008-2011 Olaf J. Schumann

  This file is part of the Cologne Laue Indexation Program.
  For more information, see <http://clip4.sf.net>

  Clip is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 3 of the License, or
  (at your option) any later version.

  Clip is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see http://www.gnu.org/licenses/
  or write to the Free Software Foundation, Inc., 51 Franklin Street,
  Fifth Floor, Boston, MA 02110-1301, USA.
 **********************************************************************/

#ifndef DEFS_H
#define DEFS_H

// Will be generated by make via call to HG
extern const char* HG_REPRO_ID;
extern const char* HG_REPRO_REV;
extern const char* HG_REPRO_DATE;
extern const char* BUILD_DATE;
extern const char* BUILD_TIME;
extern const char* QT_BUILD_VERSION;
extern const char* QT_RUN_VERSION;
extern const char* CXX_VERSION_STR;

#define VER_FILEVERSION             4,0,0,3
#define VER_FILEVERSION_STR         "4.0.0.3\0"

#define VER_PRODUCTVERSION          4,0,0,3
#define VER_PRODUCTVERSION_STR      "4.0 RC1\0"

#define VER_COMPANYNAME_STR         ""
#define VER_FILEDESCRIPTION_STR     "Software for evaluation of Laue diffraction images"
#define VER_INTERNALNAME_STR        "Cologne Laue Indexation Program"
#define VER_LEGALCOPYRIGHT_STR      "Copyright © 2008-2011 Olaf J. Schumann"
#define VER_LEGALTRADEMARKS1_STR    "Published under the termes of the Gnu Public License"
#define VER_LEGALTRADEMARKS2_STR    ""
#define VER_ORIGINALFILENAME_STR    "Clip.exe"
#define VER_PRODUCTNAME_STR         "Clip"

#define VER_COMPANYDOMAIN_STR       "clip4.sf.net"


#endif // DEFS_H
